.TH DRYOINIT 3 2026-06-25 "libdryox 1.2" "libdryox Manual"
.\" Welcome to dryoinit's manpage! As with most things I write, I attempt
.\" to make this as readable and clear as possible so one may learn from it.
.\"
.\" For any content questions about the manpage, refer to man-pages(7).
.\"
.\" The NAME section:
.\" "Name" uses nothing special here, just raw text.
.\"
.SH NAME
dryoinit, dryoinit_external - XDG standard path and file initialization
.\"
.\" The LIBRARY section:
.\" "Library" uses .RI (Roman, italic alternating) here to alternate between
.\" the Roman components (the parenthesis, the comma within quotes). It runs
.\" in order. Roman, italic, roman, italic, etc, separated by spaces, which
.\" are not rendered by the groff interpreter (usually man).
.\"
.SH LIBRARY
Dryox Core Library
.RI ( libdryox ", " \-ldryox )
.\"
.\" The SYNOPSIS section:
.\" "Synopsis" uses similar macros to Library. In any case, one should refer to
.\" groff_man for info on the macros themselves.
.\"
.\" One item of particular note here is that "quotations" can be used to control
.\" where the alternations happen. That use was present in Library, but it's
.\" clearer here.
.\"
.SH SYNOPSIS

.SH DESCRIPTION
.SH RETURN VALUE
.SH ERRORS
.SH ENVIRONMENT
.SH EXAMPLE
.SH SEE ALSO
